In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])
c = np.array([a,b,[5,6,7,8]])
print(c)
d= np.array([1,2,3])
f = np.array([1,2,3])

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]


In [29]:
c.shape

(3, 4)

In [28]:
2 * b

array([ 6,  8, 10, 12])

In [4]:
(1-d).reshape(-1,1) -1


array([[-1],
       [-2],
       [-3]])